# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: setup SSH keys and known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.REPO_REPACKAGE }}"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: install x
        run: |
          eval "$(curl https://get.x-cmd.com)"
          ls -lR  /home/runner/.x-cmd.root/v/latest

      - name: clone repository
        run: git clone git@github.com:x-cmd-pkg/yanfa.git
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: run x-cmd yanfa
        run: |
          bash ./yanfa/.x-cmd/index