# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.REPO_REPACKAGE }}
      git_user: tzw-my
      git_email: tzw@x-cmd.com

    # steps:
      # Runs a set of commands using the runners shell
      # - name: setup SSH keys and known_hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts
      #     ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      #     ssh-add - <<< "${{ secrets.REPO_REPACKAGE }}"
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock


      # - name: clone repository
      #   run: git clone git@github.com:x-cmd-pkg/yanfa.git
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            git clone git@github.com:x-cmd-pkg/yanfa.git
            [ -f ./yanfa/.x-cmd/index ] || ls
            bash ./yanfa/.x-cmd/index || true

      # - name: run x-cmd yanfa
      #   run: |
      #     bash ./yanfa/.x-cmd/index
